*: configuration improvements
nspcc-dev/neo-bench pull request #34
Opened 2020-09-14 15:03 UTC by AnnaShaleva

1. Generate nodes configurations
2. Remove unnecessary SharpSingle+GoRPC configuration
3. Add Make targets for standard test runs

2020-09-14 17:40 UTC, roman-khimov requested changes

2020-09-14 17:40 UTC, roman-khimov commented on .docker/ir/sharp.protocol.template.yml
> +#@ end
Please add newline

2020-09-14 17:40 UTC, roman-khimov commented on Makefile
> +		&& ../ytt -f ../.docker/ir/go.protocol.template.yml | go run ./config/ --node go
I think it's better integrate this into `config` tool rather than installing `ytt`.

2020-09-14 17:40 UTC, roman-khimov commented on .gitignore
> +.docker/ir/sharp.config.*.json
Newline>

2020-09-14 17:40 UTC, roman-khimov commented on README.md
> +    config   Generate configurations for single-node and four-nodes networks from scaffolds
from templates.

2020-09-14 17:40 UTC, roman-khimov commented on Makefile
> +	make stop
Newline.

2020-09-17 18:05 UTC, roman-khimov reviewed
It's not that bad actually (ytt), some duplication is annoying but that still is better than what we have now.

2020-09-17 18:05 UTC, roman-khimov commented on Makefile
> +dump.single: deps config single.acc
`.docker/build/single.acc`?

2020-09-17 18:05 UTC, roman-khimov commented on Makefile
> +dump: deps config dump.acc
`.docker/build/dump.acc`?

2020-09-18 10:58 UTC, AnnaShaleva commented on Makefile
> +dump.single: deps config single.acc
It also depends on `cmd/dump/main.go` and `cmd/dump/chain.go` as we'd like to re-generate dumps after changing these two files. So as a result we have the following:
```
dump.single: deps config .docker/build/single.acc cmd/dump/main.go cmd/dump/chain.go
```
Is it OK?

2020-09-18 11:00 UTC, AnnaShaleva commented
> It's not that bad actually (ytt), some duplication is annoying but that still is better than what we have now.

I also placed the common C# and Go configurations into special separate data file in order to avoid code duplication.

2020-09-18 13:00 UTC, roman-khimov approved these changes

2020-09-18 13:00 UTC, merged