cmd, plot: plot milliseconds per block
nspcc-dev/neo-bench pull request #39
Opened 2020-09-24 12:27 UTC by AnnaShaleva

2020-09-24 12:46 UTC, roman-khimov requested changes

2020-09-24 12:46 UTC, roman-khimov commented on cmd/bench/main.go
> +	for attempt := 0; attempt < 30; attempt++ {
Can't we make it depending on configured per-block time?

2020-09-24 12:46 UTC, roman-khimov commented on cmd/bench/main.go
> +		time.Sleep(time.Second)
Half a second?

2020-09-24 12:46 UTC, roman-khimov commented on cmd/bench/main.go
> +		log.Fatalf("Blocks were not processed for a long time since test start")
`timeout waiting for a new empty block`

2020-09-24 12:46 UTC, roman-khimov commented on plot.py
> +# files batch is a dictionary {plot_name:(DefaultMillisecondsPerBlock, [[log_file, legend_string, line colour],...])}
It duplicates node's configuration. Can we avoid that?

2020-09-25 13:21 UTC, AnnaShaleva commented on cmd/bench/main.go
> +	for attempt := 0; attempt < 30; attempt++ {
Are we OK with 10 attempts and an interval = defaultMSPerBlock?

2020-09-25 13:22 UTC, AnnaShaleva commented on cmd/bench/main.go
> +		time.Sleep(time.Second)
DefaultMSPerBlock?

2020-09-25 13:27 UTC, AnnaShaleva commented on plot.py
> +# files batch is a dictionary {plot_name:(DefaultMillisecondsPerBlock, [[log_file, legend_string, line colour],...])}
Bench and nodes configurations are split apart and bench isn't aware of the network configuration (single or multiple nodes). I tried to pass MSPerBlock as an argument to the runner.sh, but it was quite painful to pars configurations to get MSPerBlock. 

In the end I came to the other solution: just mount the corresponding configuration for the bench.

2020-09-25 16:30 UTC, roman-khimov requested changes

2020-09-25 16:30 UTC, roman-khimov commented on cmd/bench/main.go
> +		time.Sleep(time.Duration(msPerBlock) * time.Millisecond)
What I wanted to get here by making it less than `msPerBlock` is smoother test start. The first block is a bit special in that we don't push transactions all the time between it and the previous one, so we either need to throw it away from results or try to minimize the time frame between the previous block and worker threads start. Making it `/2` or even `/4` would help with this.

And waiting for more than 4*msPerBlock is probably a waste of time, either the nodes produce blocks or they don't. Initially there is no load on the system, so should be creating them on time.

2020-09-25 16:59 UTC, AnnaShaleva commented on plot.py
> +    '4 nodes 1000 rate':[["Go4x1_rate_1000.log", "go", 'blueviolet'],
Yes, I just removed them.

2020-09-25 19:15 UTC, roman-khimov approved these changes

2020-09-25 19:15 UTC, merged