Update neo-go version
nspcc-dev/neo-bench pull request #50
Opened 2020-12-08 09:59 UTC by fyrchik

Related #49 .
Need to wait until preview4 to update C# nodes.

2020-12-08 11:05 UTC, roman-khimov commented
>  Need to wait until preview4 to update C# nodes.

I don't think so, they should work fine with latest NEP-17 PRs merged. The trick here is exactly to make it all work as of current state of both nodes (and they're relatively synchronized at the moment).

2020-12-08 13:00 UTC, fyrchik commented
@roman-khimov the problem is that C# docker file requires release tarball, and I haven't found if built for master.

2020-12-08 13:05 UTC, roman-khimov commented
See Dockerfile.sharp.sources.from_binaries (and Dockerfile.sharp.sources.from_local_dependencies, though that might be more involved, it's OK to have just the first one for now).

2020-12-09 11:22 UTC, fyrchik commented
There are two unmerged PRs https://github.com/neo-project/neo-node/pull/681 https://github.com/neo-project/neo/pull/2083 . Because of incompatible container fails to be built. I'll try using `git` instead of downloading zip files.

2020-12-09 11:43 UTC, roman-khimov commented
Just leave neo-vm at compatible commit, it hasn't been changed functionally for quite some time and we certainly don't need .NET 5.0 at the moment.

2020-12-11 10:21 UTC, fyrchik commented
Updated `neo` to commit right before introduction of management contract and `neo-vm` right before dotnet 5.0 update. Everything builds, though nodes accepted by C# node are empty. Nothing is logged, currently investigating.

2020-12-11 15:39 UTC, fyrchik commented
Both nodes build and run bench. But C# node accepts only 512 tx per block. Seems like policy contract invoke somehow failed.

2020-12-11 20:21 UTC, roman-khimov commented on .docker/ir/docker-compose.single.sharp.yml
> +      driver: "journald"
NACK.

2020-12-11 20:21 UTC, roman-khimov commented on Makefile
>  #DF_SHARP=.docker/build/Dockerfile.sharp.sources.from_binaries
I thought this one is easier to make work actually.

2020-12-11 20:22 UTC, roman-khimov commented
> But C# node accepts only 512 tx per block.

Well, why is that?

2020-12-14 10:49 UTC, fyrchik commented
The problem is in invalid policy contract hash (on a commit previous to management contract introduction).

2020-12-14 14:19 UTC, fyrchik commented
The problem was in contract hashes. Commit for `neo-go` with fix is from https://github.com/nspcc-dev/neo-go/pull/1616 . Another thing is increased cost of `transfer` (TBD fix in `neo-go`).

2020-12-15 07:54 UTC, AnnaShaleva requested changes

2020-12-15 07:54 UTC, AnnaShaleva commented on .docker/build/Dockerfile.sharp.sources.from_local_dependencies
> +ENV NEOBRANCH="2e6350136dd9cd36cc0804845b2eedd75a053a7f"
If building from local dependencies works, then building from binaries should work too. Could you also update Dockerfile.sharp.sources.from_binaries?

2020-12-16 14:28 UTC, fyrchik commented on .docker/build/Dockerfile.sharp.sources.from_local_dependencies
> +ENV NEOBRANCH="2e6350136dd9cd36cc0804845b2eedd75a053a7f"
Fixed.

2020-12-16 14:29 UTC, fyrchik commented
Updated `neo-go` and `neo` to master, `neo-vm` is still one commit behind `.NET` update.

2020-12-16 15:24 UTC, AnnaShaleva requested changes

2020-12-16 15:24 UTC, AnnaShaleva commented on .docker/build/Dockerfile.golang
> +ARG REV="44b4c929922240a91a535c054da6f071f6c7ad64"
Could you, please, update Go revision to ecdf95d5d6d8fc648ebbece74f8294e62201b765? It is more recent than 44b4c929922240a91a535c054da6f071f6c7ad64 and contains mempool bugfix which is important for bench.

2020-12-16 15:53 UTC, AnnaShaleva approved these changes

2020-12-16 15:53 UTC, roman-khimov approved these changes
If all the logic changes needed are in place, we'd rather merge it as is to unblock #52. Changing neo-go revision is rather trivial.

2020-12-16 15:54 UTC, merged