Allow to benchmark GAS transfers
nspcc-dev/neo-bench pull request #80
Opened 2021-08-17 14:00 UTC by fyrchik

Close #77 .
Current syntax: `make BENCH_TYPE=gas gen` (default is `BENCH_TYPE=neo`).

2021-08-17 14:06 UTC, roman-khimov reviewed
We better have two separate tx dumps for two test modes. Then it'd be easy to switch between them (no regeneration needed).

Does it differ much from NEO on your machine?

2021-08-17 14:07 UTC, roman-khimov commented
Also I'm thinking about removing `make` from test runs, the more options like this we have the more it's inappropriate for the task.

2021-08-17 19:54 UTC, roman-khimov commented
> Does it differ much from NEO on your machine?

Just some 3% faster on mine. I'd expect to see bigger difference based on the fact that moving NEO actually also triggers GAS distribution so it's like moving two tokens with one transaction. And NEO balance decoding/encoding costs much more than GAS. Looks like memory management optimizations are still very much relevant for the node (but not critical now).

2021-08-18 06:33 UTC, AnnaShaleva commented on Makefile
> +		&& go run ./gen -type $(BENCH_TYPE) -out ../$@
I think this feature and default behaviour should be mentioned in README.

2021-08-28 12:27 UTC, fyrchik commented
I have found a problem with this: for some reason pprof still shows NEO transfers. Investigating.

2021-08-28 13:10 UTC, fyrchik commented
This happened after rebase on  #87 because I forgot to provide `-i` arguments to `runner.sh`. Fixed this in last commit.

2021-08-29 12:24 UTC, roman-khimov commented
NEOBENCH_LOGGER should default to none to avoid this:
```
$ NEOBENCH_TYPE=NEP17 make start.GoSingle10wrk
...
WARNING: The NEOBENCH_LOGGER variable is not set. Defaulting to a blank string.
...
2021/08/29 12:18:59 Init 10 workers / 5m0s time limit (1000000 txs will try to send)
2021/08/29 12:19:00 empty block: 11
2021/08/29 12:19:00 empty block: 12
2021/08/29 12:19:01 CPU: 17.995%, Mem: 137.863MB
2021/08/29 12:19:03 CPU: 0.002%, Mem: 137.414MB
2021/08/29 12:19:05 CPU: 0.002%, Mem: 137.090MB
2021/08/29 12:19:07 CPU: 0.002%, Mem: 138.012MB
2021/08/29 12:19:09 CPU: 0.002%, Mem: 137.984MB
2021/08/29 12:19:11 CPU: 0.416%, Mem: 138.242MB
```
Also, when running as `NEOBENCH_TYPE=NEP17 make start.GoSingle10wrk` it regenerates tx file (same thing with GAS).

2021-08-29 19:06 UTC, roman-khimov commented on Makefile
> +	NEOBENCH_TYPE=NEP17 make gen.NEP17
Please don't call `make` from make. It's trivial to handle with dependencies.

2021-08-31 09:46 UTC, fyrchik commented
@roman-khimov have your tried the last commit? `NEOBENCH_LOGGER` should be taken from `.env` and the problem with regeneration should also be fixed now (at least it is ` Read 1000000 txs from /dump.txs` on my laptop). The regeneration right before the docker-compose is expected (an is current master or 3.0.2 behaviour).

2021-08-31 09:46 UTC, fyrchik commented on Makefile
> +	NEOBENCH_TYPE=NEP17 make gen.NEP17
It was hard with environment variables, fixed with wildcards.

2021-08-31 14:45 UTC, roman-khimov commented on Makefile
> +		&& go run ./gen -type $* -out ../$(BUILD_DIR)/dump.$*.txs
`-out ../$@`?

2021-08-31 14:45 UTC, roman-khimov commented on Makefile
> +prepare.single: stop gen.$(NEOBENCH_TYPE) $(BUILD_DIR)/single.acc
It should depend on `$(BUILD_DIR)/dump.$(NEOBENCH_TYPE).txs`, because `gen.$(...)` should be PHONY.

2021-08-31 14:45 UTC, roman-khimov commented on cmd/bench/main.go
> +		dump = internal.Generate(ctx, internal.NEOTransfer, count)
Throw error here? I'd expect dump creation be the standard prerequisite. Otherwise it should take `NEOBENCH_TYPE` into account.

2021-08-31 14:45 UTC, roman-khimov commented on cmd/dump/tokencontract/token.go
> +package tokencontract
Can we avoid copying this contract?

2021-09-01 07:11 UTC, fyrchik commented on cmd/dump/tokencontract/token.go
> +package tokencontract
It is a bit different than example contract: we have a different owner and mint funds in `_deploy`. We certainly can avoid having it in repo, but I think it is not a big deal.

2021-09-01 07:40 UTC, roman-khimov commented on cmd/dump/tokencontract/token.go
> +package tokencontract
If there are any updates we'll have to change two contracts.

2021-09-01 08:25 UTC, fyrchik commented on Makefile
> +		&& go run ./gen -type $(BENCH_TYPE) -out ../$@
Fixed

2021-09-01 13:33 UTC, roman-khimov requested changes

2021-09-01 13:33 UTC, roman-khimov commented on cmd/bench/main.go
> -)
What's that? Why in 9b8192e584968bfd2332e71d800cccb3b8d93c53?

2021-09-01 13:33 UTC, roman-khimov commented on cmd/bench/main.go
> +		log.Fatalf("Transactions dump file wasn't specified.")
It's better to rework db11cad0638fe70c0c77632960774cd35fda1141 then, it has nothing to do with 9b8192e584968bfd2332e71d800cccb3b8d93c53 anyway.

2021-09-01 13:33 UTC, roman-khimov commented on Makefile
> +prepare.single: stop $(BUILD_DIR)/dump.$(NEOBENCH_TYPE).txs  $(BUILD_DIR)/single.acc
Additional spaces are not really needed.

2021-09-01 13:33 UTC, roman-khimov commented on cmd/dump/main.go
> +	txDeploy, err := newDeployTx(bc, priv, "./dump/tokencontract/token.nef",
Of course you've written where this NEF comes from and how to regenerate it if needed?

2021-09-01 15:53 UTC, fyrchik commented on cmd/bench/main.go
> -)
`count` is no longer used, these numbers too (used for generation before).

2021-09-02 13:37 UTC, roman-khimov approved these changes

2021-09-02 13:37 UTC, merged